-- What the morning report said, kept.
--
-- `report` computes its findings every night and prints them to the journal,
-- where they are read once and are then only grep-able. The history cannot be
-- rebuilt out of `coffee` afterwards: that table holds current state, and the
-- delisting pass rewrites `last_seen_at` across it every night.
--
-- No unique constraint, on purpose. The only key available is
-- (day, kind, site, summary), and `summary` is a free-text sentence with the
-- night's numbers in it; a constraint over it would make the wording part of
-- the schema. `report` instead deletes the day's rows and re-inserts them in
-- one transaction, which is idempotent without that.

CREATE TABLE IF NOT EXISTS crawl_finding (
    -- An identity column with the primary key declared inline, for the reason
    -- `crawl_run` records: adding a PRIMARY KEY to a table that already has
    -- one raises invalid_table_definition, which the duplicate_* blocks below
    -- do not trap, while inside CREATE TABLE IF NOT EXISTS the whole statement
    -- is a no-op on a second apply.
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The crawl day as a UTC date, the calendar price_history.seen_on already
    -- uses, so the two tables join without a cast.
    day date NOT NULL,
    kind text NOT NULL,
    -- '' for a catalogue-wide finding, which is what Finding.site already is.
    site text NOT NULL,
    severity text NOT NULL,
    summary text NOT NULL,
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    recorded_at timestamp with time zone NOT NULL DEFAULT now()
);

-- "What did last night say", and the severity-over-time series behind it: both
-- read one day or a range of days, newest first.
CREATE INDEX IF NOT EXISTS crawl_finding_day_idx
    ON crawl_finding (day DESC, severity, kind);
-- "What has this shop been doing all week", which the day index cannot answer
-- without reading every finding of every day in the window.
CREATE INDEX IF NOT EXISTS crawl_finding_site_day_idx
    ON crawl_finding (site, day DESC);
